FROM ubuntu:20.04

ARG   DEBIAN_FRONTEND=noninteractive
RUN   apt-get update \
&&  apt-get install -y gosu libnss-ldapd build-essential libssl-dev curl
RUN   curl -LO https://github.com/krallin/tini/releases/download/v0.18.0/tini
RUN   mv tini /sbin/tini
RUN   chmod +x /sbin/tini
RUN apt-get update \
&& DEBIAN_FRONTEND=noninteractive \
&& apt-get install --no-install-recommends -y \
        python3-pip 
RUN pip install xvfbwrapper
RUN apt-get update \
&& DEBIAN_FRONTEND=noninteractive \
&& apt-get install --no-install-recommends -y \
  gcc g++ make sudo \
  build-essential --no-install-recommends apt-utils \
  zip unzip curl man wget make emacs vim \
  libffi-dev libzbar-dev libzbar0 libxml2-dev libxslt-dev python3-dev python3-lxml \
  nodejs yarn\
  software-properties-common coreutils \
  python3-pytest-xvfb python3-xvfbwrapper xvfb \
&& apt-get clean \
&& rm -rf /var/lib/apt/lists/*
RUN apt-get update \
&& apt-add-repository ppa:git-core/ppa \
&& apt-get update \
&& apt-get install --no-install-recommends git -y \
&& apt-get clean \
&& rm -rf /var/lib/apt/lists/*
 
WORKDIR /opt/
RUN curl -fsSL -o Miniconda3-Linux-x86_64.sh https://repo.anaconda.com/miniconda/Miniconda3-latest-Linux-x86_64.sh \
&& bash Miniconda3-Linux-x86_64.sh -b -p /opt/miniconda \
&& rm -rf Miniconda3-Linux-x86_64.sh
ENV PATH /opt/miniconda/bin:$PATH
RUN conda init \
&& conda update --all \
&& conda config --append channels conda-forge \
&& conda install -y nodejs


RUN python -m pip --no-cache-dir install \
  jupyterlab==3.6.5 \
  jupyter_client==7.1.1 \
  terminado==0.12.1 \
  jupyterlab-git==0.42.0 \
  jupyterlab_theme_solarized_dark==2.0.1 \
  qtconsole==5.2.2 \
  IPython==8.15.0 \
  nbclient==0.8.0 \
  notebook==6.4.7 \
  matplotlib==3.5.1 \
  pandas==1.4.0 \
  ipykernel==6.25.2 \
  ipyleaflet==0.17.3 \
  qtpy==2.0.0 \
  ipywidgets==8.1.0 \
  jupyterlab_widgets==3.0.8 \
  lxml==4.9.3 \
  flask-cors==3.0.10 \
  beautifulsoup4==4.10.0 \
  configparser==5.2.0 \
  ipyevents==2.0.1 \
  astroquery==0.4.5 \
  astropy==6.0.0 \
&& jupyter labextension install jupyter-matplotlib --no-build \
&& jupyter labextension install jupyter-leaflet --no-build \
&& jupyter labextension disable "@jupyterlab/apputils-extension:announcements" \
&& jupyter lab build --minimize=False \
&& python -m pip --no-cache-dir install pyesasky==1.9.5 \
&& jupyter labextension install pyesasky --no-build \
&& jupyter lab build --minimize=False \
&& jupyter nbextension install --py pyesasky --sys-prefix \
&& jupyter nbextension enable --py pyesasky --sys-prefix \
&& jupyter lab build --minimize=False \
&& ln -s /opt/miniconda/etc/profile.d/conda.sh /etc/profile.d/conda.sh


# To ensure bash is used
SHELL ["/bin/bash", "-c"]

COPY run.sh /opt/run.sh
COPY run_simplified.sh /opt/run_simplified.sh
RUN chmod a+x /opt/run*.sh
####
CMD [ "/bin/bash", "-c", "/opt/run_simplified.sh" ]
